// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.7
// source: wire.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Step:
	//	*Step_File
	//	*Step_Up
	//	*Step_Down
	Step isStep_Step `protobuf_oneof:"step"`
}

func (x *Step) Reset() {
	*x = Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (m *Step) GetStep() isStep_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (x *Step) GetFile() *StepFile {
	if x, ok := x.GetStep().(*Step_File); ok {
		return x.File
	}
	return nil
}

func (x *Step) GetUp() *StepPathUp {
	if x, ok := x.GetStep().(*Step_Up); ok {
		return x.Up
	}
	return nil
}

func (x *Step) GetDown() *StepPathDown {
	if x, ok := x.GetStep().(*Step_Down); ok {
		return x.Down
	}
	return nil
}

type isStep_Step interface {
	isStep_Step()
}

type Step_File struct {
	File *StepFile `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type Step_Up struct {
	Up *StepPathUp `protobuf:"bytes,2,opt,name=up,proto3,oneof"`
}

type Step_Down struct {
	Down *StepPathDown `protobuf:"bytes,3,opt,name=down,proto3,oneof"`
}

func (*Step_File) isStep_Step() {}

func (*Step_Up) isStep_Step() {}

func (*Step_Down) isStep_Step() {}

type StepFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode    uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Own     uint32 `protobuf:"varint,6,opt,name=own,proto3" json:"own,omitempty"`
	Grp     uint32 `protobuf:"varint,7,opt,name=grp,proto3" json:"grp,omitempty"`
	Size    uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Hash    []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	HashErr string `protobuf:"bytes,5,opt,name=hashErr,proto3" json:"hashErr,omitempty"`
}

func (x *StepFile) Reset() {
	*x = StepFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFile) ProtoMessage() {}

func (x *StepFile) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFile.ProtoReflect.Descriptor instead.
func (*StepFile) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

func (x *StepFile) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StepFile) GetOwn() uint32 {
	if x != nil {
		return x.Own
	}
	return 0
}

func (x *StepFile) GetGrp() uint32 {
	if x != nil {
		return x.Grp
	}
	return 0
}

func (x *StepFile) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StepFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepFile) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *StepFile) GetHashErr() string {
	if x != nil {
		return x.HashErr
	}
	return ""
}

type StepPathUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Up uint32 `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
}

func (x *StepPathUp) Reset() {
	*x = StepPathUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepPathUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepPathUp) ProtoMessage() {}

func (x *StepPathUp) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepPathUp.ProtoReflect.Descriptor instead.
func (*StepPathUp) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

func (x *StepPathUp) GetUp() uint32 {
	if x != nil {
		return x.Up
	}
	return 0
}

type StepPathDown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Down string `protobuf:"bytes,1,opt,name=down,proto3" json:"down,omitempty"`
}

func (x *StepPathDown) Reset() {
	*x = StepPathDown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepPathDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepPathDown) ProtoMessage() {}

func (x *StepPathDown) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepPathDown.ProtoReflect.Descriptor instead.
func (*StepPathDown) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{3}
}

func (x *StepPathDown) GetDown() string {
	if x != nil {
		return x.Down
	}
	return ""
}

var File_wire_proto protoreflect.FileDescriptor

var file_wire_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x77, 0x69,
	0x72, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12, 0x24, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x77, 0x69, 0x72, 0x65,
	0x2e, 0x53, 0x74, 0x65, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x22, 0x0a, 0x02, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x50, 0x61, 0x74, 0x68, 0x55, 0x70, 0x48,
	0x00, 0x52, 0x02, 0x75, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x50,
	0x61, 0x74, 0x68, 0x44, 0x6f, 0x77, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x64, 0x6f, 0x77, 0x6e, 0x42,
	0x06, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x22, 0x98, 0x01, 0x0a, 0x08, 0x53, 0x74, 0x65, 0x70,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x72,
	0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x72, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x68,
	0x45, 0x72, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x61, 0x73, 0x68, 0x45,
	0x72, 0x72, 0x22, 0x1c, 0x0a, 0x0a, 0x53, 0x74, 0x65, 0x70, 0x50, 0x61, 0x74, 0x68, 0x55, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x75, 0x70,
	0x22, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x65, 0x70, 0x50, 0x61, 0x74, 0x68, 0x44, 0x6f, 0x77, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x6f, 0x77, 0x6e, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x79, 0x69, 0x79, 0x75, 0x69, 0x2f, 0x68, 0x69, 0x6e, 0x6f, 0x6d, 0x6f,
	0x72, 0x69, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData = file_wire_proto_rawDesc
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(file_wire_proto_rawDescData)
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wire_proto_goTypes = []interface{}{
	(*Step)(nil),         // 0: wire.Step
	(*StepFile)(nil),     // 1: wire.StepFile
	(*StepPathUp)(nil),   // 2: wire.StepPathUp
	(*StepPathDown)(nil), // 3: wire.StepPathDown
}
var file_wire_proto_depIdxs = []int32{
	1, // 0: wire.Step.file:type_name -> wire.StepFile
	2, // 1: wire.Step.up:type_name -> wire.StepPathUp
	3, // 2: wire.Step.down:type_name -> wire.StepPathDown
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wire_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepPathUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepPathDown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_wire_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Step_File)(nil),
		(*Step_Up)(nil),
		(*Step_Down)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wire_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_rawDesc = nil
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
